export const dna = {
  concept: "dna",
  property: "a specific lineup of chemical base pairs along its strand",
  cluster: [
    {
      cluster_label: ["necklace", "pendant", "strand", "earring", "helix"],
      vehicle: [
        "twine",
        "strand",
        "earring",
        "ring",
        "cord",
        "necklace",
        "tree",
        "pendant",
        "corkscrew",
        "yarn",
        "helix",
        "bracelet",
        "rope",
        "string",
      ],
      meaning: {
        necklace: "Some explanation in the tooltip",
        pendant: "Some explanation in the tooltip",
        strand: "Some explanation in the tooltip",
        earring: "Some explanation in the tooltip",
        helix: "Some explanation in the tooltip",
      },
      explanation: {},
    },
    {
      cluster_label: ["maze", "labyrinth", "honeycomb", "staircase", "path"],
      vehicle: [
        "honeycomb",
        "labyrinth",
        "cycle",
        "beehive",
        "snake",
        "chain",
        "journey",
        "path",
        "ladder",
        "staircase",
        "program",
        "maze",
        "body",
        "river",
        "spiral",
        "blueprint",
        "stack",
        "universe",
        "set",
        "loop",
        "highway",
        "recipe",
        "code",
        "road",
        "mystery",
        "circle",
        "quest",
        "book",
        "spring",
        "map",
        "story",
        "key",
        "building",
        "puzzle",
      ],
      meaning: {},
      explanation: {
        recipe: {
          raw: 'DNA is the recipe. The base pairs are the ingredients, and the sequence of base pairs is the order in which they must be added. The DNA polymerase is the chef, adding new base pairs to the DNA strand. The DNA helicase is the mixer, separating the DNA strands so that the polymerase can add new base pairs. The DNA ligase is the glue, sealing the DNA strand back together.',
          writing: 'DNA is the recipe for life. It contains the instructions for building proteins, which are the building blocks of all living things. The DNA molecule is made up of two strands of sugar and phosphate molecules, which are held together by pairs of nitrogen-containing molecules called bases.\n\nThe sequence of bases in DNA determines the sequence of amino acids in proteins. Amino acids are the building blocks of proteins, and they are arranged in a particular order to form specific proteins.\n\nDNA is like a recipe because it contains the instructions for building proteins. The bases are like the ingredients in a recipe, and the sequence of bases is like the order in which they must be added. The DNA polymerase is like the chef, adding new base pairs to the DNA strand. The DNA helicase is like the mixer, separating the DNA strands so that the polymerase can add new base pairs. The DNA ligase is like the glue, sealing the DNA strand back together."',
        },
        book: {
          raw: 'DNA is the book. The nucleotides are the letters, spelling out the genetic code. The sugar-phosphate backbone is the spine of the book, holding everything together. The base pairs are the pages, with the information written on them. The double helix is the structure of the book, with the two strands winding around each other.',
          writing: '"DNA is the molecule that contains the genetic instructions for the development and function of living organisms. DNA is a double-stranded molecule held together by weak bonds between the bases, or nucleotides, on each strand. The bases are arranged in a specific order, and the order of the bases determines the function of the DNA.\n\nThe DNA molecule is like a book. The nucleotides are the letters, spelling out the genetic code. The sugar-phosphate backbone is the spine of the book, holding everything together. The base pairs are the pages, with the information written on them. The double helix is the structure of the book, with the two strands winding around each other.\n\nThe DNA molecule is made up of two strands of nucleotides, which are held together by weak bonds between the bases. The order of the bases on each strand determines the function of the DNA. The two strands of DNA are coiled around each other to form a double helix."',
        },
        staircase: {
          raw: 'DNA is the staircase. The double helix is the structure of the staircase, with the rungs being the base pairs. The nucleotides are the steps, going up and down the staircase. The sugar-phosphate backbone is the handrail, keeping everything in place.',
          writing: '"The double helix structure of DNA is held together by weak hydrogen bonds between the bases. The bases are arranged in a specific order, with adenine (A) always paired with thymine (T), and cytosine (C) always paired with guanine (G). This order is what encodes the information in DNA. The sequence of bases determines the order of amino acids in proteins, which in turn determine the structure and function of the protein.\n\nDNA is like a staircase, with the base pairs being the rungs and the sugar-phosphate backbone being the handrail. The nucleotides are the steps, going up and down the staircase. This metaphor can help you understand the structure of DNA and how the sequence of bases encodes information."',
        },
        map: {
          raw: 'DNA is the map of a city. The base pairs are the streets, laid out in a specific order. The genes are the landmarks, telling us where everything is. The chromosomes are the districts, grouping related genes together. The DNA molecule is the city itself, containing all the information needed to build and maintain a living organism.',
          writing: 'DNA is the map of a city. The base pairs are the streets, laid out in a specific order. The genes are the landmarks, telling us where everything is. The chromosomes are the districts, grouping related genes together. The DNA molecule is the city itself, containing all the information needed to build and maintain a living organism.\n\nEach cell in our bodies contains a complete set of instructions for how that cell should look and function. This instruction book is stored in our DNA, in the form of a code made up of four chemical letters: A, T, C, and G. The order of these letters, known as the DNA sequence, determines the instructions for building each cell.\n\nDNA is like a long ladder, with the rungs made up of these chemical letters. The sides of the ladder are made of sugar and phosphate molecules. The rungs are held together by weak bonds between the letters.\n\nThe DNA molecule is very long and thin, about two millionths of a millimeter wide. If you were to stretch out the DNA in all the cells in your body, it would be about two meters long!\n\nThe DNA code is read in units of three letters, called codons. Each codon specifies a particular amino acid, which are the building blocks of proteins. There are 64 possible codons, which can be divided into 20 different amino acids.\n\nThe DNA sequence is read from the beginning of the molecule to the end, in a linear fashion. The sequence is then used to build the proteins needed by the cell. Proteins are the machines that carry out the cell\'s functions.',
        },
        building: {
          raw: 'DNA is a set of instructions for building a house. The DNA molecule is the blueprint, containing all the information needed to build the house. The nucleotides are the building blocks, the basic units that make up the DNA molecule. The chromosomes are the construction workers, assembling the nucleotides into DNA molecules. The genes are the architects, designing the DNA molecule.',
          writing: 'DNA is a set of instructions for building a house. The DNA molecule is the blueprint, containing all the information needed to build the house. The nucleotides are the building blocks, the basic units that make up the DNA molecule. The chromosomes are the construction workers, assembling the nucleotides into DNA molecules. The genes are the architects, designing the DNA molecule.\n\nThe DNA molecule is a long, double-stranded chain of nucleotides. The nucleotides are joined together by covalent bonds between the phosphate group of one nucleotide and the sugar group of the next nucleotide. The sequence of nucleotides in a DNA molecule determines the sequence of amino acids in a protein.\n\nThe DNA molecule is divided into two parts: the coding region and the non-coding region. The coding region is the part of the DNA molecule that contains the instructions for making a protein. The non-coding region is the part of the DNA molecule that does not contain the instructions for making a protein.\n\nThe coding region is divided into genes. Each gene contains the instructions for making a specific protein. The proteins made by the genes are responsible for the structure and function of the cells."',
        },

      }
    },
    {
      cluster_label: ["chromosome", "nucleus", "gene", "molecule", "cell"],
      vehicle: [
        'gene',
        'molecule',
        'cell',
        'chromosome',
        'nucleus',
      ],
      meaning: {},
      explanation: {},
    },
  ],
};
